microblogging/urls.py
from django.urls import path
from microblogging import views
app_name = 'microblogging'


urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='log_in'),
    path('logout/', views.logout_view, name='log_out'),
    path('post/<int:pk>', views.post_detail, name="post_detail"),
    path('newpost/', views.new_post, name='new_post'),
    path('delete/<int:pk>', views.post_delete, name="post_delete")
]

microlly/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('microblogging.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microblogging/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.


#class Users(models.Model):
#    username = models.CharField(max_length=20, null=False, blank=False)
#    password = models.CharField(max_length=100, null=False, blank=False)
#    first_name = models.CharField(max_length=20, null=True, blank=False)
#    last_name = models.CharField(max_length=20, null=True, blank=False)
#    email = models.CharField(max_length=50, null=True, blank=False)
#
#    class Meta:
#        verbose_name = 'Utilisateur'
#        verbose_name_plural = 'Utilisateurs'

class Post(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    body = models.TextField(null=False, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(default='default-slug')
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 0
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'

microblogging/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from microblogging.models import Post


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='')
    last_name = forms.CharField(max_length=30, required=True, help_text='')
    email = forms.EmailField(max_length=254, required=True, help_text='')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class NewPost(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'body')

microblogging/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from microblogging.models import Post
from microblogging.forms import SignUpForm, NewPost
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import get_object_or_404


# Create your views here.

def index(request):
    post = Post.objects.all().order_by('-update_date')
    return render(request, 'index.html', {'latests_posts': post})

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('microblogging:index')
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form})


def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('microblogging:index')
    else:
        form = AuthenticationForm()
    return render(request, 'log_in.html', {'form':form})

def logout_view(request):
    logout(request)
    return redirect('microblogging:index')
    
def post_detail(request, pk):
    post = get_object_or_404(Post,pk=pk) #recup donnée dans la bdd
    return render(request, 'post.html', {'post':post}) 

def new_post(request):
    form = NewPost(data=request.POST)
    if form.is_valid():
        result = form.save(commit=False)
        result.author = request.user
        result.save()
        return redirect('microblogging:index')
    else:
        form = NewPost()
    return render(request, 'newpost.html', {'form':form})


def post_delete(request, pk):
    post = get_object_or_404(Post,pk=pk)
    post.delete()
    return redirect('microblogging:index') 

microblogging/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
        <meta charset="utf-8">
        <title>Microlly</title>

        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w"
                crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style_base.css' %}" />
        <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.ico' %}" />

<body>
        <div class="pure-g">
                <div class="pure-u-1-5"></div>
                <div class="pure-u-3-5" id="body_div">
                        <div class="navbar">
                                <h1 style="text-align: center">Microblogging</h1>
                                <ul>
                                        <li>
                                                <form class="form-inline" action="{% url 'microblogging:index' %}"
                                                        method="POST">
                                                        {% csrf_token %}
                                                        <button class="btn btn-outline-light" type="submit">HOME</button>
                                                </form>
                                        </li>

                                        <li>
                                                <form class="form-inline" action="{% url 'microblogging:register' %}"
                                                        method="POST">
                                                        {% csrf_token %}
                                                        <button class="btn btn-outline-light" type="submit">Register</button>
                                                </form>
                                        </li>

                                        <li>
                                                {%if user.is_authenticated %}
                                                        <form class="form-inline" action="{% url 'microblogging:log_out' %}"
                                                                method="POST">
                                                                {% csrf_token %}
                                                                <button class="btn btn-outline-light" type="submit">Logout</button>
                                                        </form>       
                                                {% else %}
                                                        <form class="form-inline" action="{% url 'microblogging:log_in' %}"
                                                                method="POST">
                                                                {% csrf_token %}
                                                                <button class="btn btn-outline-light" type="submit">Login</button>
                                                        </form>
                                                {% endif %}
                                        </li>
                                        {%if user.is_superuser %}
                                                <a href="/admin">Admin</a>
                                        {% endif %}

                                </ul>
                        </div>
                        <div class="content">
                                
                                {% block content %}
                                {% endblock %}
                        </div>
                </div>
                <div class="pure-u-1-5"></div>
        </div>
</body>

</html>

microblogging/templates/index.html
{% extends "_base.html" %}
{% block content %}


{% if user.is_authenticated %}
    <p>Welcome {{ user.username }}</p>
    <form class="form-inline" action="{% url 'microblogging:new_post' %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-outline-light" type="submit">New Post</button>
    </form>
{% endif %}

{% if latests_posts %}
    <article class="list_posts">
        {% for post in latests_posts %}
        <div class="post_list">
            <a href="{% url 'microblogging:post_detail' post.pk %}">
                <h3>{{post.title}}</h3>
            </a>
            <small>{{post.author}} - {{post.update_date}}</small>
        </div>
        <p></p>
        {% endfor %}
    </article>
{% else %}
    <h1>Pas de cotenu ici ¯\_(ツ)_/¯</h1>
{% endif %}

{% endblock %}

microblogging/templates/log_in.html
{% extends '_base.html' %}
{% block content %}

<form action="{% url 'microblogging:log_in' %}" method="POST">
    {% csrf_token %}
    {{form}}

    <button type="submit">Login</button>
</form>

{% endblock %}

microblogging/templates/newpost.html
{% extends '_base.html' %}
{% block content %}

<form class="new_post" action="{% url 'microblogging:new_post' %}" method="POST">
    {% csrf_token %}
    {{form}}

    <button type="submit">Save new post</button>
</form>



{% endblock %}

microblogging/templates/post.html
{% extends "_base.html" %}
{% block content %}
<div class="post_container">
    <div class="post">
        <div class="post_title">
            <h1>{{post.title}}</h1>
        </div>
        
        <div class="post_body">
            {{post.body}}
        </div>
        
        <div class="post_infos">
            <small>
                {{post.author}}
                {{post.update_date}}
                {% if post.update_date > post.creation_date %}
                    edited.
                {% endif %}
            </small>
        </div>
    </div>
    {% if user == post.author or user.is_superuser %}
    <div class="flex">
        <form class="form-inline" action="{% url 'microblogging:post_delete' post.pk %}"
            method="POST">
            {% csrf_token %}
            <button class="btn btn-outline-light" type="submit">Delete</button>
        </form>
    </div>
    
    {% endif %}
</div>

{% endblock %}

microblogging/templates/register.html
{% extends '_base.html' %}

{% block content %}
<form action="{% url 'microblogging:register' %}" method="POST">
    
    {% csrf_token %}
    {{form}}
    <button type="submit"> Register </button>
</form>

{% endblock %}